config/routes.rb
Rails.application.routes.draw do
  resources :statuses

  resources :appointments

  resources :diagnostics

  resources :invoices

  resources :patients do
    member do
      get 'patients'
    end
  end

  resources :employees do
    member do
      get 'employees'
    end
  end

  resources :physicians

  resources :insurances
  get 'dash/front'

  root 'dash#front'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :invoices

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:employee_name, :employee_address, :city, :state, :zip_code, :employee_email, :employee_phone, :social_security)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>


  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :employee_name %><br>
    <%= f.text_field :employee_name %>
  </div>
  <div class="field">
    <%= f.label :employee_address %><br>
    <%= f.text_field :employee_address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip_code %><br>
    <%= f.text_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :employee_email %><br>
    <%= f.text_field :employee_email %>
  </div>
  <div class="field">
    <%= f.label :employee_phone %><br>
    <%= f.text_field :employee_phone %>
  </div>
  <div class="field">
    <%= f.label :social_security %><br>
    <%= f.text_field :social_security %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <thead>
    <tr>
      <th>Employee name</th>
      <th>Employee address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip code</th>
      <th>Employee email</th>
      <th>Employee phone</th>
      <th>Social security</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.employee_name %></td>
        <td><%= employee.employee_address %></td>
        <td><%= employee.city %></td>
        <td><%= employee.state %></td>
        <td><%= employee.zip_code %></td>
        <td><%= employee.employee_email %></td>
        <td><%= employee.employee_phone %></td>
        <td><%= employee.social_security %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee name:</strong>
  <%= @employee.employee_name %>
</p>

<p>
  <strong>Employee address:</strong>
  <%= @employee.employee_address %>
</p>

<p>
  <strong>City:</strong>
  <%= @employee.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @employee.state %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @employee.zip_code %>
</p>

<p>
  <strong>Employee email:</strong>
  <%= @employee.employee_email %>
</p>

<p>
  <strong>Employee phone:</strong>
  <%= @employee.employee_phone %>
</p>

<p>
  <strong>Social security:</strong>
  <%= @employee.social_security %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>