config/routes.rb
Rails.application.routes.draw do
  resources :statuses

  resources :appointments

  resources :diagnostics

  resources :invoices

  resources :patients do
    member do
      get 'patients'
    end
  end

  resources :employees do
    member do
      get 'employees'
    end
  end

  resources :physicians

  resources :insurances
  get 'dash/front'

  root 'dash#front'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :patient
  belongs_to :diagnostic
  belongs_to :physician
  belongs_to :status
  belongs_to :invoice

  validate :date, uniqueness: true
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  respond_to :html
  def index
    @appointments = Appointment.all
    respond_with(@appointments)
  end


  # GET /appointments/1
  # GET /appointments/1.json
  def show
    @appointment = Appointment.find(params[:id])

    respond_to do |format|
      format.html
      format.pdf do
        pdf = ReportPdf.new(@appointment)


        send_data pdf.render, filename: "Appointment_Invoice_#(@appointment.id).pdf",
                  type: "application/pdf",
                  disposition:"inline"
      end
    end
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:physician_id, :patient_id, :date, :reason, :note, :diagnostic_id)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :physician_id %><br>
    <%= f.collection_select :physician_id, Physician.all, :id,:physician_name, :prompt => "Select one" %>
  </div>
  <div class="field">
    <%= f.label :patient_id %><br>
    <%= f.collection_select :patient_id, Patient.all, :id, :patient_name, :prompt => "Select one"  %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date, :id => "datetimepicker_mask"  %>
    <script>
        $( "#datetimepicker_mask" ).(datetimepicker);
    </script>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_area :reason %>
  </div>t
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.label :diagnostic_id %><br>
    <%= f.collection_select :diagnostic_id, Diagnostic.all, :id, :description, :prompt => "Select one" %>
  </div>
    <div class="field">
      <%= f.label :status %><br>
      <%= f.collection_select :status_id, Status.all, :id, :status_name, :prompt => "Select one"  %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<h1>Listing appointments</h1>

<table>
  <thead>
    <tr>
      <th>Physician</th>
      <th>Patient</th>
      <th>Date</th>
      <th>Reason</th>
      <th>Note</th>
      <th>Diagnostic</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.physician.physician_name %></td>
        <td><%= appointment.patient.patient_name %></td>
        <td><%= appointment.date %></td>
        <td><%= appointment.reason %></td>
        <td><%= appointment.note %></td>
        <td><%= appointment.diagnostic.description %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Printible Recepit (PDF)', appointment_path(appointment, format: "pdf") %></td>
      </tr>

    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<table id="notice"><%= notice %>

<tr>
  <td>Physician:</td>
  <td>Patient:</td>
  <td>Date:</td>
  <td>Reason:</td>
  <td>Note:</td>
  <td>Diagnostic:</td>


</tr>

  <tr>
    <td> <%= @appointment.patient.patient_name %>:</td>
    <td>  <%= @appointment.date %>:</td>
    <td>  <%= @appointment.reason %>      :</td>
    <td>  <%= @appointment.note %>      :</td>
    <td>  <%= @appointment.diagnostic.description %>      :</td>
    <td>  <%= @appointment.diagnostic.description %>      :</td>
  </tr>

</table>




<%= link_to 'Edit', edit_appointment_path(@appointment) %> |

   <%= link_to 'Back', appointments_path %>