config/routes.rb
Rails.application.routes.draw do
  resources :statuses

  resources :appointments

  resources :diagnostics

  resources :invoices

  resources :patients do
    member do
      get 'patients'
    end
  end

  resources :employees do
    member do
      get 'employees'
    end
  end

  resources :physicians

  resources :insurances
  get 'dash/front'

  root 'dash#front'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :patient
  belongs_to :diagnostic
  belongs_to :physician
  belongs_to :status
  belongs_to :invoice

  validate :date, uniqueness: true
end

app/models/diagnostic.rb
class Diagnostic < ActiveRecord::Base
  has_one :appointment

  validates_presence_of :fee
  validates(:fee, :numericality => {:greater_than_or_equal_to => 0, :message => 'Positive amount only'})
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :invoices

end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
 has_many :patients
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  has_one :appointment
  belongs_to :employee
  belongs_to :appointment
end

app/models/patient.rb
class Patient < ActiveRecord::Base
 belongs_to :insurance
  has_many :appointments
  has_many :physicians, through: :appointments
end

app/models/physician.rb
class Physician < ActiveRecord::Base
  has_many :appointments
  has_many :patients, through: :appointments
  belongs_to :diagnostic_code



end

app/models/status.rb
class Status < ActiveRecord::Base
has_many :appointments
end

app/controllers/dash_controller.rb
class DashController < ApplicationController

  def front

  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:employee_id, :appointment_id, :total)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:patient_name, :patient_address, :city, :state, :zip_code, :patient_email, :patient_phone, :insurance_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>


    <%= csrf_meta_tags %>




  </head>



  </head>

  <body>




  <nav class="top-bar" data-options="is_hover:false" >
    <ul class="title-area">
      <!-- Title Area -->
      <li class="name">
        <h1><a href="#">H-TOWN Dermatologists</a></h1>
      </li>
      <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Left Nav Section -->
      <ul class="left">
        <li class="divider"></li>
        <li> <%= link_to "Employees", employees_path %></li>
        <li class="divider"></li>
        <li class="divider"></li>
        <li> <%= link_to "Patient", patients_path %></li>
        <li class="divider"></li>
        <li><%= link_to "Appointment", appointments_path %></li>
        <li class="divider"></li>
        <li><%= link_to "Physician", physicians_path %></li>
      </ul>



      <ul class="right">
          <li class="has-dropdown">
          <a href="#">Admin</a>


          <ul id="hover" class="has-dropdown" >

            <li class="active"> <%= link_to "Edit Diagnostic", diagnostics_path %></li>
            <li class="active"><%= link_to "Edit Appointment", appointments_path %></li>
            <li class="active"><%= link_to "Edit Physician", physicians_path %></li>
          </ul>
        </li>
      </ul>
    </section>
  </nav>


    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>